=== imrafaelmerino/json-values/benchmarking/src/main/resources/personSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "required": [
    "firstName",
    "lastName",
    "age",
    "latitude",
    "longitude",
    "fruits",
    "numbers",
    "vegetables"
  ],
  "properties": {
    "firstName": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "lastName": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "age": {
      "type": "integer",
      "minimum": 0,
      "maximum": 110
    },
    "latitude": {
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "longitude": {
      "type": "number",
      "minimum": -180,
      "maximum": 180
    },
    "fruits": {
      "type": "array",
      "minItems": 1,
      "maxItems": 100,
      "items": {
        "type": "string"
      }
    },
    "numbers": {
      "type": "array",
      "minItems": 1,
      "maxItems": 100,
      "items": {
        "type": "integer"
      }
    },
    "vegetables": {
      "type": "array",
      "minItems": 1,
      "maxItems": 100,
      "items": {
        "$ref": "#/definitions/veggie"
      }
    }
  },
  "definitions": {
    "veggie": {
      "type": "object",
      "required": [
        "veggieName",
        "veggieLike"
      ],
      "properties": {
        "veggieName": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "veggieLike": {
          "type": "boolean"
        }
      }
    }
  }
}

=== imrafaelmerino/json-values/benchmarking/src/main/resources/person.json
{
  "firstName": "John",
  "lastName": "Doe",
  "age": 21,
  "latitude": 48.858093,
  "longitude": 2.294694,
  "fruits": [
    "apple",
    "orange",
    "pear"
  ],
  "numbers": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10
  ],
  "vegetables": [
    {
      "veggieName": "potato",
      "veggieLike": true
    },
    {
      "veggieName": "broccoli",
      "veggieLike": false
    },
    {
      "veggieName": "broccoli",
      "veggieLike": false
    }
  ]
}
